-- ═══════════════════════════════════════════════════════════════════
-- 0082  Product customization on the consolidator
-- ═══════════════════════════════════════════════════════════════════
-- Shares the product customization catalog (option groups/values, presets,
-- product assignments, rules, premium tiers, per-size overrides, discountable
-- rules, report groups) across terminals, like items and discounts.
--
-- App side: CustomizationWriteThrough (lib/modules/product_customization/
-- consolidator/customization_write_through.dart). With sync_maintenance_data
-- on, writes go here first and are mirrored into local sqlite; the realtime
-- listener re-pulls on any change; reads stay local.
--
-- Columns mirror the local sqlite schema (db v81) exactly, because Upload
-- pushes whole local rows. Local BOOLEAN columns hold 0/1, so they are
-- SMALLINT here. Ids are kept across terminals (rows reference each other by
-- id); Upload seeds explicit ids, so resync_maintenance_sequences() is
-- extended below to move each identity past MAX(id).
--
-- FKs mirror local ones EXCEPT those to item.barcode: an item re-seed on the
-- consolidator must not cascade-wipe customization.
--
-- Applied MANUALLY against Supabase (see consolidator-migrations-manual).

-- ── Tables (parents first) ──────────────────────────────────────────

CREATE TABLE IF NOT EXISTS option_value_presets (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  created_at  TEXT DEFAULT (now()::text),
  updated_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS option_groups (
  id                             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                           TEXT NOT NULL,
  is_required                    SMALLINT NOT NULL DEFAULT 0,
  selection_type                 INTEGER NOT NULL DEFAULT 0,
  max_select                     INTEGER,
  min_select                     INTEGER DEFAULT 0,
  value_preset_id                BIGINT REFERENCES option_value_presets(id) ON DELETE SET NULL,
  is_variant                     SMALLINT NOT NULL DEFAULT 0,
  show_current_item_as_default   SMALLINT NOT NULL DEFAULT 0,
  default_variant_alias          TEXT,
  variant_group_select_one_text  TEXT,
  updated_at                     TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS option_values (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  value_preset_id   BIGINT REFERENCES option_value_presets(id) ON DELETE CASCADE,
  option_group_id   BIGINT REFERENCES option_groups(id) ON DELETE CASCADE,
  alias             TEXT,
  barcode           TEXT NOT NULL,
  price_delta       DOUBLE PRECISION DEFAULT 0.0,
  cost_price_delta  DOUBLE PRECISION DEFAULT 0.0,
  quantity          DOUBLE PRECISION DEFAULT 1.0,
  unit              INTEGER DEFAULT 1,
  display_order     INTEGER DEFAULT 0,
  is_premium        SMALLINT NOT NULL DEFAULT 0,
  updated_at        TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_option_values_group ON option_values(option_group_id);
CREATE INDEX IF NOT EXISTS idx_option_values_preset ON option_values(value_preset_id);

CREATE TABLE IF NOT EXISTS option_group_presets (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  created_at  TEXT DEFAULT (now()::text),
  updated_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS option_group_preset_groups (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_preset_id  BIGINT NOT NULL REFERENCES option_group_presets(id) ON DELETE CASCADE,
  option_group_id  BIGINT NOT NULL REFERENCES option_groups(id) ON DELETE CASCADE,
  display_order    INTEGER DEFAULT 0,
  updated_at       TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS product_option_group_assignments (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  barcode          TEXT NOT NULL,
  group_preset_id  BIGINT REFERENCES option_group_presets(id) ON DELETE CASCADE,
  option_group_id  BIGINT REFERENCES option_groups(id) ON DELETE CASCADE,
  display_order    INTEGER DEFAULT 0,
  is_override      SMALLINT NOT NULL DEFAULT 0,
  updated_at       TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_pog_assignments_barcode ON product_option_group_assignments(barcode);

-- No FK on target_group_id / target_value_id, matching local: the app deletes
-- a group's rules itself (OptionGroupDao cascade).
CREATE TABLE IF NOT EXISTS option_group_rules (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_group_name  TEXT NOT NULL,
  target_group_id    BIGINT NOT NULL,
  trigger_value      TEXT NOT NULL,
  action             TEXT NOT NULL DEFAULT 'disable',
  target_value_id    BIGINT,
  updated_at         TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS option_group_premium_tier (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  option_group_id  BIGINT NOT NULL REFERENCES option_groups(id) ON DELETE CASCADE,
  premium_count    INTEGER NOT NULL,
  surcharge        DOUBLE PRECISION NOT NULL,
  updated_at       TIMESTAMPTZ DEFAULT now(),
  UNIQUE (option_group_id, premium_count)
);

CREATE TABLE IF NOT EXISTS product_discountable_rule (
  id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_barcode            TEXT NOT NULL UNIQUE,
  discountable_cap_amount    DOUBLE PRECISION NOT NULL,
  trigger_min_premium_count  INTEGER NOT NULL DEFAULT 1,
  updated_at                 TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS product_option_value_overrides (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_barcode   TEXT NOT NULL,
  option_value_id   BIGINT NOT NULL REFERENCES option_values(id) ON DELETE CASCADE,
  option_group_id   BIGINT,
  alias             TEXT,
  price_delta       DOUBLE PRECISION,
  cost_price_delta  DOUBLE PRECISION,
  quantity          DOUBLE PRECISION,
  unit              INTEGER,
  is_premium        SMALLINT,
  updated_at        TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_povo_barcode ON product_option_value_overrides(product_barcode);
CREATE UNIQUE INDEX IF NOT EXISTS uq_povo_full
  ON product_option_value_overrides(product_barcode, COALESCE(option_group_id, -1), option_value_id);

CREATE TABLE IF NOT EXISTS report_groups (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  is_active   SMALLINT NOT NULL DEFAULT 1,
  updated_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS report_group_values (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id    BIGINT NOT NULL REFERENCES report_groups(id) ON DELETE CASCADE,
  label       TEXT NOT NULL,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  updated_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS report_group_members (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  value_id    BIGINT NOT NULL REFERENCES report_group_values(id) ON DELETE CASCADE,
  barcode     TEXT NOT NULL,
  updated_at  TIMESTAMPTZ DEFAULT now(),
  UNIQUE (value_id, barcode)
);

-- ── Realtime (full rows on UPDATE/DELETE) ───────────────────────────

DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'option_value_presets', 'option_groups', 'option_values', 'option_group_presets',
    'option_group_preset_groups', 'product_option_group_assignments', 'option_group_rules',
    'option_group_premium_tier', 'product_discountable_rule', 'product_option_value_overrides',
    'report_groups', 'report_group_values', 'report_group_members'
  ] LOOP
    EXECUTE format('ALTER TABLE %I REPLICA IDENTITY FULL', t);
    BEGIN
      EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE %I', t);
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
  END LOOP;
END $$;

-- ── Sequence resync (0036 body + customization tables) ──────────────

CREATE OR REPLACE FUNCTION resync_maintenance_sequences() RETURNS void AS $$
DECLARE t TEXT;
BEGIN
  -- Identity-PK tables: bump the sequence to MAX(pk).
  PERFORM setval(pg_get_serial_sequence('"Department"', 'dept_id'),
                 GREATEST((SELECT COALESCE(MAX(dept_id), 0) FROM "Department"), 1), true);
  PERFORM setval(pg_get_serial_sequence('"Category"', 'category_id'),
                 GREATEST((SELECT COALESCE(MAX(category_id), 0) FROM "Category"), 1), true);
  PERFORM setval(pg_get_serial_sequence('item', 'id'),
                 GREATEST((SELECT COALESCE(MAX(id), 0) FROM item), 1), true);

  -- Dual "code = id" tables share one sequence between the two columns.
  PERFORM setval(pg_get_serial_sequence('"Discount"', 'id'),
                 GREATEST((SELECT COALESCE(MAX(id), 0) FROM "Discount"),
                          (SELECT COALESCE(MAX(disc_code), 0) FROM "Discount"), 1), true);
  PERFORM setval(pg_get_serial_sequence('charge_payment', 'id'),
                 GREATEST((SELECT COALESCE(MAX(id), 0) FROM charge_payment),
                          (SELECT COALESCE(MAX(charge_code), 0) FROM charge_payment), 1), true);
  PERFORM setval(pg_get_serial_sequence('bank', 'id'),
                 GREATEST((SELECT COALESCE(MAX(id), 0) FROM bank),
                          (SELECT COALESCE(MAX(bank_code), 0) FROM bank), 1), true);

  -- Product customization (0082): all identity `id` PKs seeded with local ids.
  FOREACH t IN ARRAY ARRAY[
    'option_value_presets', 'option_groups', 'option_values', 'option_group_presets',
    'option_group_preset_groups', 'product_option_group_assignments', 'option_group_rules',
    'option_group_premium_tier', 'product_discountable_rule', 'product_option_value_overrides',
    'report_groups', 'report_group_values', 'report_group_members'
  ] LOOP
    EXECUTE format(
      'SELECT setval(pg_get_serial_sequence(%L, ''id''), GREATEST((SELECT COALESCE(MAX(id), 0) FROM %I), 1), true)',
      t, t);
  END LOOP;
END;
$$ LANGUAGE plpgsql;

GRANT EXECUTE ON FUNCTION resync_maintenance_sequences() TO anon, authenticated;

SELECT resync_maintenance_sequences();
