-- Per Order slip mode (replaces 'consolidated').
--
-- 'consolidated' printed exactly like 'perItem': the ingest trigger runs once per
-- sales_order_item row and queued one print_job per line. 'perOrder' instead:
--
--   * order_round_ticket — ONE scannable code ('O' + seq) per kitchen round
--     (a kds_orders row = one save/batch, so a later add-on round gets a new code).
--   * One slip per (round, printer): the first line opens a print_job held back
--     2s via next_attempt_at; later lines of the round for that printer append
--     to it while it is still pending and unattempted. Every printer's slip
--     carries the same orderTicketCode.
--   * Per-line order_item_ticket rows are still minted (not printed), so
--     serve_tickets, reprints and the order-scanning app keep working.
--   * get_order_ticket / dispatch_order_ticket — the KDS dispatch dialog: look
--     the round up by code, then hand over chosen quantities of any of its lines
--     (any station), advancing the kitchen line (kds_serve_units) and the sales
--     line exactly like serve_ticket does.
--
-- A stored 'consolidated' is rewritten to 'perOrder' (and treated as it below,
-- for terminals that have not updated yet).
--
-- Functions copied verbatim from 0064 with only the perOrder additions:
--   kds_ingest_sales_order_item, kds_enqueue_reprint_slip
--
-- Idempotent. Applied MANUALLY against Supabase (see consolidator-migrations-manual).

-- ── Round ticket ─────────────────────────────────────────────────
CREATE SEQUENCE IF NOT EXISTS order_round_ticket_code_seq;

CREATE TABLE IF NOT EXISTS order_round_ticket (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_code    TEXT UNIQUE NOT NULL
                 DEFAULT ('O' || to_char(nextval('order_round_ticket_code_seq'), 'FM000000')),
  kds_order_id   BIGINT UNIQUE NOT NULL REFERENCES kds_orders(id) ON DELETE CASCADE,
  sales_order_id BIGINT,
  status         TEXT NOT NULL DEFAULT 'open',   -- 'open' | 'completed'
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at   TIMESTAMPTZ
);

ALTER TABLE print_job
  ADD COLUMN IF NOT EXISTS order_round_ticket_id BIGINT;

CREATE INDEX IF NOT EXISTS idx_print_job_round_ticket
  ON print_job (order_round_ticket_id, status)
  WHERE order_round_ticket_id IS NOT NULL;

-- ── Mode rename ──────────────────────────────────────────────────
UPDATE app_config
   SET value = jsonb_set(value, '{mode}', '"perOrder"')
 WHERE key = 'web_order_slip_mode' AND value->>'mode' = 'consolidated';

-- ── Ingest (0064 + perOrder) ─────────────────────────────────────
CREATE OR REPLACE FUNCTION kds_ingest_sales_order_item()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_delta                    NUMERIC(12, 2);
  m                          RECORD;   -- item catalog row
  rp                         RECORD;   -- resolved printer (kds_resolve_line_printer)
  v_category                 TEXT;
  v_slot                     TEXT;
  v_label                    TEXT;
  v_print_target_client_id   TEXT;     -- device that prints the slip (may be a POS)
  v_display_target_client_id TEXT;     -- station that displays the card (KDS only)
  v_zone_id                  BIGINT;   -- effective (post-fallback) print zone
  v_zone_name                TEXT;
  v_so_number                BIGINT;
  v_table_id                 BIGINT;
  v_order_type               INTEGER;
  v_eff_order_type           INTEGER;  -- per-item override when tagged, else header
  v_table_name               TEXT;
  v_order_number             TEXT;
  v_client_id                TEXT;
  v_cashier_name             TEXT;     -- who punched the line (added_by, else order opener)
  v_batch_key                TEXT;
  v_sequence                 INTEGER;
  v_kds_order_id             BIGINT;
  v_kds_item_id              BIGINT;
  v_ticket_code              TEXT;
  v_copies                   INTEGER := 1;
  v_payload                  JSONB;
  v_slip_mode                TEXT;
  v_units                    INTEGER;
  v_ticket_qty               NUMERIC(12, 2);
  i                          INTEGER;
  v_round_ticket_id          BIGINT;   -- perOrder: the round's shared ticket
  v_round_code               TEXT;
  v_job_id                   BIGINT;
  v_line                     JSONB;
BEGIN
  v_delta := NEW.quantity - COALESCE(NEW.printed_quantity, 0);
  IF v_delta <= 0 THEN
    RETURN NULL;
  END IF;

  SELECT i.barcode, i.item_desc, i.print_desc, i.category, i.non_vat, i.show_on_kds,
         i.estimated_prep_time, i.assigned_printer, i.assigned_printer_client_id
    INTO m
    FROM item i
   WHERE i.barcode = NEW.item_barcode;

  IF NOT FOUND OR COALESCE(m.show_on_kds, 1) <> 1 THEN
    UPDATE sales_order_item SET printed_quantity = NEW.quantity
     WHERE order_item_id = NEW.order_item_id;
    RETURN NULL;
  END IF;

  SELECT c.category_desc INTO v_category
    FROM "Category" c WHERE c.category_id = m.category;

  -- Sales-order header first: the table decides the print zone.
  SELECT so.so_number, so.table_id, so.order_type
    INTO v_so_number, v_table_id, v_order_type
    FROM sales_order_2 so WHERE so.sales_order_id = NEW.sales_order_id;

  SELECT z.o_zone_id, z.o_zone_name INTO v_zone_id, v_zone_name
    FROM resolve_print_zone(v_table_id) z;

  -- Home printer → zone remap → label / print target / display target.
  SELECT * INTO rp
    FROM kds_resolve_line_printer(v_zone_id, m.assigned_printer, m.assigned_printer_client_id);
  v_slot                     := rp.o_slot;
  v_label                    := rp.o_label;
  v_print_target_client_id   := rp.o_print_client_id;
  v_display_target_client_id := rp.o_display_client_id;

  v_eff_order_type := COALESCE(NEW.order_type, v_order_type);

  v_order_number := COALESCE(v_so_number::text, NEW.sales_order_id::text);
  IF v_table_id IS NOT NULL THEN
    SELECT t.table_desc INTO v_table_name FROM tables t WHERE t.table_id = v_table_id;
  END IF;

  SELECT client_id INTO v_client_id FROM pos_clients WHERE client_id = NEW.pos_client_id;

  -- Cashier = whoever punched this line (added_by); fall back to the user who
  -- opened the order. Stamped on the card so reprints carry it too (0064).
  SELECT u.name INTO v_cashier_name
    FROM "user" u
   WHERE u.id = COALESCE(NEW.added_by,
                         (SELECT so.created_by FROM sales_order_2 so
                           WHERE so.sales_order_id = NEW.sales_order_id));

  v_batch_key := COALESCE(NULLIF(btrim(NEW.kds_batch_id), ''), 'so:' || NEW.sales_order_id::text);

  SELECT id INTO v_kds_order_id FROM kds_orders WHERE kds_batch_id = v_batch_key;
  IF v_kds_order_id IS NULL THEN
    SELECT count(*) + 1 INTO v_sequence FROM kds_orders WHERE order_number = v_order_number;

    INSERT INTO kds_orders (kds_batch_id, sales_order_id, pos_client_id, order_number,
                            table_number, customer_name, order_sequence,
                            print_zone_id, print_zone_name, cashier_name)
    VALUES (v_batch_key, NEW.sales_order_id, v_client_id, v_order_number,
            v_table_name, NEW.customer_name, v_sequence,
            v_zone_id, v_zone_name, v_cashier_name)
    ON CONFLICT (kds_batch_id) DO NOTHING;

    SELECT id INTO v_kds_order_id FROM kds_orders WHERE kds_batch_id = v_batch_key;
  END IF;

  INSERT INTO kds_order_items (
    order_id, name, quantity, barcode, category, estimated_prep_time,
    assigned_printer, printer_label, target_client_id, customization, modifiers, order_item_id,
    order_type, order_type_desc, note, station_printer, station_printer_client_id
  ) VALUES (
    v_kds_order_id, COALESCE(m.print_desc, m.item_desc), v_delta::int, m.barcode, v_category,
    m.estimated_prep_time, v_slot, v_label, v_display_target_client_id, NEW.customization, NEW.item_modifiers,
    NEW.order_item_id, NEW.order_type, NEW.order_type_desc, NEW.note,
    rp.o_station_slot, rp.o_station_client_id
  ) RETURNING id INTO v_kds_item_id;

  SELECT value->>'mode' INTO v_slip_mode FROM app_config WHERE key = 'web_order_slip_mode';

  -- ── Per Order (0084) ──────────────────────────────────────────
  -- One slip per (round, printer) carrying every line, and ONE shared code for
  -- the whole round across all printers. The per-line ticket is still minted
  -- (unprinted) so serve_tickets / reprints keep working.
  IF v_slip_mode IN ('perOrder', 'consolidated') THEN
    INSERT INTO order_round_ticket (kds_order_id, sales_order_id)
    VALUES (v_kds_order_id, NEW.sales_order_id)
    ON CONFLICT (kds_order_id) DO NOTHING;
    SELECT id, ticket_code INTO v_round_ticket_id, v_round_code
      FROM order_round_ticket WHERE kds_order_id = v_kds_order_id;
    -- A line added to a round that was already fully dispatched reopens it.
    UPDATE order_round_ticket SET status = 'open', completed_at = NULL
     WHERE id = v_round_ticket_id AND status = 'completed';

    INSERT INTO order_item_ticket (order_item_id, sales_order_id, quantity, kds_order_item_id)
    VALUES (NEW.order_item_id, NEW.sales_order_id, v_delta, v_kds_item_id);

    v_line := jsonb_build_object(
      'productBarcode',      m.barcode,
      'productName',         m.item_desc,
      'receiptName',         COALESCE(m.print_desc, m.item_desc),
      'quantity',            v_delta::int,
      'price',               NEW.amount,
      'orderTypeCode',       COALESCE(v_eff_order_type, 1),
      'orderType',           NEW.order_type_desc,
      'assignedPrinter',     v_slot,
      'nonVat',              (COALESCE(m.non_vat, 0) = 1),
      'specialInstructions', NEW.special_instructions,
      'note',                NEW.note,
      'assignedTableName',   v_table_name,
      'zoneName',            v_zone_name,
      'customerName',        NEW.customer_name,
      'cashierName',         v_cashier_name,
      'orderNumber',         v_order_number,
      'orderTicketCode',     v_round_code,
      'orderItemId',         NEW.order_item_id
    );

    -- Merge window: the POS writes a round's lines as separate rows, so the
    -- first line opens a job held back ~2s (claim_print_jobs honours
    -- next_attempt_at, 0077) and later lines for the same printer append to it
    -- while it is still pending and unattempted.
    SELECT j.id INTO v_job_id
      FROM print_job j
     WHERE j.order_round_ticket_id = v_round_ticket_id
       AND j.printer_name = v_slot
       AND j.target_client_id IS NOT DISTINCT FROM v_print_target_client_id
       AND j.status = 'pending'
       AND COALESCE(j.attempts, 0) = 0
     ORDER BY j.id DESC
     LIMIT 1
     FOR UPDATE SKIP LOCKED;

    IF v_job_id IS NOT NULL THEN
      UPDATE print_job
         SET payload         = jsonb_set(payload, '{orders}', (payload->'orders') || jsonb_build_array(v_line)),
             next_attempt_at = now() + INTERVAL '2 seconds'
       WHERE id = v_job_id;
    ELSE
      v_payload := jsonb_build_object(
        'orders',          jsonb_build_array(v_line),
        'tableId',         v_table_id,
        'zoneName',        v_zone_name,
        'simpleWebSlip',   true,
        'orderTicketCode', v_round_code
      );
      INSERT INTO print_job (sales_order_id, printer_name, target_client_id, copies, payload,
                             order_round_ticket_id, next_attempt_at)
      VALUES (NEW.sales_order_id, v_slot, v_print_target_client_id, v_copies, v_payload,
              v_round_ticket_id, now() + INTERVAL '2 seconds');
    END IF;

    UPDATE sales_order_item SET printed_quantity = NEW.quantity
     WHERE order_item_id = NEW.order_item_id;
    RETURN NULL;
  END IF;


  IF v_slip_mode = 'perQuantity' THEN
    v_units := v_delta::int;
    v_ticket_qty := 1;
  ELSE
    v_units := 1;
    v_ticket_qty := v_delta;
  END IF;

  FOR i IN 1..v_units LOOP
    INSERT INTO order_item_ticket (order_item_id, sales_order_id, quantity, kds_order_item_id)
    VALUES (NEW.order_item_id, NEW.sales_order_id, v_ticket_qty, v_kds_item_id)
    RETURNING ticket_code INTO v_ticket_code;

    v_payload := jsonb_build_object(
      'orders', jsonb_build_array(jsonb_build_object(
        'productBarcode',      m.barcode,
        'productName',         m.item_desc,
        'receiptName',         COALESCE(m.print_desc, m.item_desc),
        'quantity',            v_ticket_qty::int,
        'price',               NEW.amount,
        'orderTypeCode',       COALESCE(v_eff_order_type, 1),
        'orderType',           NEW.order_type_desc,
        'assignedPrinter',     v_slot,
        'nonVat',              (COALESCE(m.non_vat, 0) = 1),
        'specialInstructions', NEW.special_instructions,
        'note',                NEW.note,
        'assignedTableName',   v_table_name,
        'zoneName',            v_zone_name,
        'customerName',        NEW.customer_name,
        'cashierName',         v_cashier_name,
        'servingBarcode',      v_ticket_code,
        'orderItemId',         NEW.order_item_id
      )),
      'tableId', v_table_id,
      'zoneName', v_zone_name,
      'simpleWebSlip', true
    );

    INSERT INTO print_job (sales_order_id, printer_name, target_client_id, copies, payload)
    VALUES (NEW.sales_order_id, v_slot, v_print_target_client_id, v_copies, v_payload);
  END LOOP;

  UPDATE sales_order_item SET printed_quantity = NEW.quantity
   WHERE order_item_id = NEW.order_item_id;

  RETURN NULL;
EXCEPTION WHEN OTHERS THEN
  RAISE WARNING 'kds_ingest_sales_order_item failed for order_item_id=%: %', NEW.order_item_id, SQLERRM;
  RETURN NULL;
END $$;

-- ── Reprint slip (0064 + perOrder code) ──────────────────────────
CREATE OR REPLACE FUNCTION kds_enqueue_reprint_slip(
  p_kds_item_id      BIGINT,
  p_kind             TEXT,
  p_from_table       TEXT,
  p_to_table         TEXT,
  p_target_client_id TEXT DEFAULT NULL
) RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  ki            RECORD;
  v_slot        TEXT;
  v_special     TEXT;
  v_amount      NUMERIC(12, 2);
  v_order_type  INTEGER;
  v_table_name  TEXT;
  v_ticket_code TEXT;
  v_round_code  TEXT;
  v_payload     JSONB;
BEGIN
  SELECT ki2.id, ki2.name, ki2.quantity, ki2.barcode, ki2.assigned_printer,
         ki2.order_item_id, ko.sales_order_id, ko.order_number, ko.table_number, ko.customer_name, ko.cashier_name,
         ko.print_zone_name
    INTO ki
    FROM kds_order_items ki2
    JOIN kds_orders ko ON ko.id = ki2.order_id
   WHERE ki2.id = p_kds_item_id;
  IF NOT FOUND OR COALESCE(ki.quantity, 0) <= 0 THEN
    RETURN;
  END IF;

  -- The line carries its resolved (zone-aware) printer slot.
  v_slot := COALESCE(NULLIF(btrim(ki.assigned_printer), ''), 'Unassigned');

  SELECT s.special_instructions, s.amount INTO v_special, v_amount
    FROM sales_order_item s WHERE s.order_item_id = ki.order_item_id;
  SELECT so.order_type INTO v_order_type
    FROM sales_order_2 so WHERE so.sales_order_id = ki.sales_order_id;

  SELECT ticket_code INTO v_ticket_code
    FROM order_item_ticket
   WHERE kds_order_item_id = ki.id
   ORDER BY id DESC
   LIMIT 1;

  -- Per Order rounds (0084) print the round's shared code, not the line's.
  SELECT rt.ticket_code INTO v_round_code
    FROM order_round_ticket rt
    JOIN kds_order_items k ON k.order_id = rt.kds_order_id
   WHERE k.id = ki.id;

  v_table_name := COALESCE(p_to_table, ki.table_number);

  v_payload := jsonb_build_object(
    'orders', jsonb_build_array(jsonb_build_object(
      'productBarcode',      ki.barcode,
      'productName',         ki.name,
      'receiptName',         ki.name,
      'quantity',            ki.quantity,
      'price',               COALESCE(v_amount, 0),
      'orderTypeCode',       COALESCE(v_order_type, 1),
      'assignedPrinter',     v_slot,
      'specialInstructions', v_special,
      'assignedTableName',   v_table_name,
      'zoneName',            ki.print_zone_name,
      'customerName',        ki.customer_name,
      'cashierName',         ki.cashier_name,
      'servingBarcode',      CASE WHEN v_round_code IS NULL THEN v_ticket_code END,
      'orderTicketCode',     v_round_code,
      'orderNumber',         ki.order_number,
      'orderItemId',         ki.order_item_id,
      'slipKind',            p_kind,
      'fromTableName',       p_from_table,
      'toTableName',         p_to_table
    )),
    'simpleWebSlip', true,
    'zoneName', ki.print_zone_name,
    'slipKind', p_kind
  );

  INSERT INTO print_job (sales_order_id, printer_name, target_client_id, copies, payload)
  VALUES (ki.sales_order_id, v_slot, NULLIF(btrim(p_target_client_id), ''), 1, v_payload);

EXCEPTION WHEN OTHERS THEN
  RAISE WARNING 'kds_enqueue_reprint_slip failed for kds_order_item_id=% kind=%: %',
    p_kds_item_id, p_kind, SQLERRM;
END $$;

-- ── Dispatch dialog: look up a round ─────────────────────────────
-- One row per kitchen line of the round (cancelled lines excluded), each
-- repeating the header columns. No rows = unknown code.
DROP FUNCTION IF EXISTS get_order_ticket(TEXT);
CREATE FUNCTION get_order_ticket(p_code TEXT)
RETURNS TABLE (
  ticket_code        TEXT,
  round_status       TEXT,
  order_number       TEXT,
  table_number       TEXT,
  zone_name          TEXT,
  customer_name      TEXT,
  kds_order_item_id  BIGINT,
  order_item_id      BIGINT,
  item_name          TEXT,
  quantity           NUMERIC,
  served_quantity    NUMERIC,
  item_status        TEXT,
  modifiers          TEXT,
  customization      TEXT,
  note               TEXT,
  order_type_desc    TEXT,
  station_label      TEXT,
  assigned_printer   TEXT,
  display_client_id  TEXT
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT rt.ticket_code, rt.status, ko.order_number::TEXT, ko.table_number::TEXT,
         ko.print_zone_name, ko.customer_name,
         ki.id, ki.order_item_id, ki.name, ki.quantity::NUMERIC, ki.served_quantity,
         ki.status, ki.modifiers, ki.customization, ki.note, ki.order_type_desc,
         COALESCE(NULLIF(btrim(ki.printer_label), ''), ki.assigned_printer),
         ki.assigned_printer,
         ki.target_client_id
    FROM order_round_ticket rt
    JOIN kds_orders ko      ON ko.id = rt.kds_order_id
    JOIN kds_order_items ki ON ki.order_id = rt.kds_order_id
   WHERE rt.ticket_code = upper(btrim(p_code))
     AND ki.status <> 'cancelled'
   ORDER BY ki.id;
$$;

-- ── Dispatch dialog: hand over chosen quantities ─────────────────
-- p_lines: [{"kds_order_item_id": 12, "quantity": 2}, ...]. Quantities are
-- clamped to what is still undispatched; lines outside the round are ignored.
-- Returns one row per line actually advanced (or one NULL row when nothing
-- was), each carrying round_completed.
DROP FUNCTION IF EXISTS dispatch_order_ticket(TEXT, JSONB, TEXT);
CREATE FUNCTION dispatch_order_ticket(p_code TEXT, p_lines JSONB, p_device_id TEXT DEFAULT NULL)
RETURNS TABLE (
  kds_order_item_id  BIGINT,
  item_name          TEXT,
  dispatched_qty     NUMERIC,
  status_before      TEXT,
  round_completed    BOOLEAN
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  rt        order_round_ticket%ROWTYPE;
  ln        JSONB;
  ki        kds_order_items%ROWTYPE;
  v_qty     NUMERIC;
  v_before  TEXT;
  v_done    BOOLEAN;
  v_results JSONB := '[]'::jsonb;
  r         JSONB;
BEGIN
  SELECT * INTO rt FROM order_round_ticket t
   WHERE t.ticket_code = upper(btrim(p_code))
     FOR UPDATE;
  IF NOT FOUND THEN
    RETURN;
  END IF;

  FOR ln IN SELECT * FROM jsonb_array_elements(COALESCE(p_lines, '[]'::jsonb)) LOOP
    SELECT * INTO ki FROM kds_order_items k
     WHERE k.id = (ln->>'kds_order_item_id')::BIGINT
       AND k.order_id = rt.kds_order_id
       AND k.status <> 'cancelled'
       FOR UPDATE;
    IF NOT FOUND THEN
      CONTINUE;
    END IF;

    v_qty := LEAST(COALESCE((ln->>'quantity')::NUMERIC, 0), ki.quantity - ki.served_quantity);
    IF v_qty <= 0 THEN
      CONTINUE;
    END IF;

    -- Sales line, exactly as serve_ticket advances it (0059). item_status is
    -- generated and follows automatically.
    UPDATE sales_order_item i
       SET served_quantity = LEAST(i.quantity, i.served_quantity + v_qty),
           served_at       = CASE
                               WHEN LEAST(i.quantity, i.served_quantity + v_qty) >= i.quantity
                                 THEN now()
                               ELSE i.served_at
                             END
     WHERE i.order_item_id = ki.order_item_id;

    -- Kitchen line: dispatched at full count; the order recalcs its status.
    v_before := kds_serve_units(ki.id, ki.order_item_id, v_qty);

    -- Close the line's (unprinted) per-line ticket once fully handed over, so
    -- a later T-code scan reports already_served instead of drawing it down.
    IF ki.served_quantity + v_qty >= ki.quantity THEN
      UPDATE order_item_ticket t
         SET ticket_status = 'served',
             served_at     = now(),
             served_by     = COALESCE(p_device_id, t.served_by)
       WHERE t.kds_order_item_id = ki.id
         AND t.ticket_status <> 'served';
    END IF;

    v_results := v_results || jsonb_build_array(jsonb_build_object(
      'id', ki.id, 'name', ki.name, 'qty', v_qty, 'before', v_before));
  END LOOP;

  SELECT NOT EXISTS (
    SELECT 1 FROM kds_order_items k
     WHERE k.order_id = rt.kds_order_id
       AND k.status <> 'cancelled'
       AND k.served_quantity < k.quantity
  ) INTO v_done;

  IF v_done AND rt.status <> 'completed' THEN
    UPDATE order_round_ticket SET status = 'completed', completed_at = now() WHERE id = rt.id;
  END IF;

  IF jsonb_array_length(v_results) = 0 THEN
    RETURN QUERY SELECT NULL::BIGINT, NULL::TEXT, 0::NUMERIC, NULL::TEXT, v_done;
    RETURN;
  END IF;

  FOR r IN SELECT * FROM jsonb_array_elements(v_results) LOOP
    RETURN QUERY SELECT (r->>'id')::BIGINT, r->>'name', (r->>'qty')::NUMERIC, r->>'before', v_done;
  END LOOP;
END $$;

GRANT SELECT ON order_round_ticket TO anon, authenticated;
GRANT EXECUTE ON FUNCTION get_order_ticket(TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION dispatch_order_ticket(TEXT, JSONB, TEXT) TO anon, authenticated;
