-- Local Supabase Consolidator Database Migration Schema

-- 1. Heartbeat & Client Metadata Table
CREATE TABLE IF NOT EXISTS pos_clients (
    client_id TEXT PRIMARY KEY,
    client_name TEXT NOT NULL,
    last_heartbeat TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    app_version TEXT,
    os_info TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Sales Header (sales_m1 - Based strictly on v_sales_m1 columns)
CREATE TABLE IF NOT EXISTS sales_m1 (
    pos_client_id TEXT REFERENCES pos_clients(client_id) ON DELETE CASCADE,
    tseq_no BIGINT NOT NULL,
    seq_no INTEGER NOT NULL,
    account_amt NUMERIC(12, 2) NOT NULL,
    actual_date TIMESTAMP WITH TIME ZONE NOT NULL,
    atm_amt NUMERIC(12, 2) NOT NULL,
    authorized INTEGER NOT NULL,
    balance NUMERIC(12, 2) NOT NULL,
    branch INTEGER NOT NULL,
    c_bal NUMERIC(12, 2) NOT NULL,
    card_amt NUMERIC(12, 2) NOT NULL,
    cash_amt NUMERIC(12, 2) NOT NULL,
    cashier INTEGER NOT NULL,
    change NUMERIC(12, 2) NOT NULL,
    charge_amt NUMERIC(12, 2) NOT NULL,
    check_amt NUMERIC(12, 2) NOT NULL,
    checker INTEGER NOT NULL,
    customer TEXT,
    d_tran_date TIMESTAMP WITH TIME ZONE NOT NULL,
    def_amt NUMERIC(12, 2) NOT NULL,
    del_member TEXT,
    demog TEXT,
    disc_code INTEGER NOT NULL,
    discount_a NUMERIC(12, 2) NOT NULL,
    discount_p NUMERIC(12, 2) NOT NULL,
    discountable NUMERIC(12, 2) NOT NULL,
    doc_num TEXT,
    dump INTEGER NOT NULL,
    free_reason INTEGER NOT NULL,
    gift_amt NUMERIC(12, 2) NOT NULL,
    guest_count INTEGER NOT NULL,
    i_disc_amt NUMERIC(12, 2) NOT NULL,
    l_end TEXT,
    l_nonvat INTEGER NOT NULL,
    lay_amt NUMERIC(12, 2) NOT NULL,
    lay_no INTEGER NOT NULL,
    lc NUMERIC(12, 2) NOT NULL,
    local_tax NUMERIC(12, 2) NOT NULL,
    location INTEGER NOT NULL,
    machine INTEGER NOT NULL,
    member TEXT,
    member_area TEXT,
    misc NUMERIC(12, 2) NOT NULL,
    nonvat_seq INTEGER NOT NULL,
    order_no INTEGER NOT NULL,
    order_type INTEGER NOT NULL,
    other_amt NUMERIC(12, 2) NOT NULL,
    qty INTEGER NOT NULL,
    ref_no TEXT,
    ret_ex_amt NUMERIC(12, 2) NOT NULL,
    ret_exch INTEGER NOT NULL,
    sales_m1_date TEXT NOT NULL,
    sales_m1_time TEXT NOT NULL,
    salesman INTEGER NOT NULL,
    salesman_2 INTEGER NOT NULL,
    sen_count INTEGER NOT NULL,
    seq_loc TEXT,
    status INTEGER NOT NULL,
    surcharge_a NUMERIC(12, 2) NOT NULL,
    surcharge_p NUMERIC(12, 2),
    t_price NUMERIC(12, 2) NOT NULL,
    timestamp_column TIMESTAMP WITH TIME ZONE,
    tips NUMERIC(12, 2) NOT NULL,
    tot_free_16 NUMERIC(12, 2) NOT NULL,
    trans_no INTEGER NOT NULL,
    updated TEXT,
    v_tran_type INTEGER NOT NULL,
    vat_seq INTEGER NOT NULL,
    vat_tax NUMERIC(12, 2) NOT NULL,
    vc_table TEXT,
    vip_card TEXT,
    void_seq_no INTEGER NOT NULL,
    z_amount NUMERIC(12, 2) NOT NULL,
    z_number INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (pos_client_id, tseq_no)
);

-- 3. Sales Details / Tenders (sales_m2)
CREATE TABLE IF NOT EXISTS sales_m2 (
    pos_client_id TEXT REFERENCES pos_clients(client_id) ON DELETE CASCADE,
    id BIGINT NOT NULL,
    tseq_no BIGINT NOT NULL,
    seq_no INTEGER NOT NULL,
    si_no INTEGER NOT NULL,
    date TIMESTAMP WITH TIME ZONE NOT NULL,
    time TIMESTAMP WITH TIME ZONE NOT NULL,
    barcode VARCHAR(50) NOT NULL,
    category TEXT,
    supp_code TEXT,
    dept TEXT,
    qty NUMERIC(12, 2) NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    gross_price NUMERIC(12, 2) NOT NULL,
    gross_amount NUMERIC(12, 2) NOT NULL,
    cost_price NUMERIC(12, 2) DEFAULT 0.0,
    machine INTEGER NOT NULL,
    location INTEGER NOT NULL,
    branch INTEGER NOT NULL,
    cashier INTEGER NOT NULL,
    d_tran_date TIMESTAMP WITH TIME ZONE NOT NULL,
    date_out TIMESTAMP WITH TIME ZONE NOT NULL,
    deduct NUMERIC(12, 2) NOT NULL,
    add_amt NUMERIC(12, 2) NOT NULL,
    status INTEGER NOT NULL,
    disc_type INTEGER DEFAULT 0,
    coupon_code INTEGER DEFAULT 0,
    disc_code INTEGER DEFAULT 0,
    disc_fix_amt NUMERIC(12, 2) DEFAULT 0.0,
    disc_percent NUMERIC(12, 2) DEFAULT 0.0,
    is_disc_exempt BOOLEAN DEFAULT FALSE,
    item_type INTEGER NOT NULL,
    order_type INTEGER NOT NULL,
    vat_seq INTEGER NOT NULL,
    nonvat_seq INTEGER NOT NULL,
    box_barcode VARCHAR(50),
    v_surch NUMERIC(12, 2) NOT NULL,
    timestamp_column TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    actual_date TIMESTAMP WITH TIME ZONE NOT NULL,
    rec_ctr INTEGER NOT NULL,
    vat_sale NUMERIC(12, 2) NOT NULL,
    tax_code INTEGER NOT NULL,
    vat NUMERIC(12, 2) DEFAULT 0.0,
    nonvat NUMERIC(12, 2) DEFAULT 0.0,
    vat12 NUMERIC(12, 2) DEFAULT 0.0,
    vatPriv NUMERIC(12, 2) DEFAULT 0.0,
    zero_rated NUMERIC(12, 2) DEFAULT 0.0,
    x_read_stat INTEGER NOT NULL,
    z_number INTEGER NOT NULL,
    trans_no INTEGER NOT NULL,
    posting_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    payment_deposit_amt NUMERIC(12, 2),
    customization_sequence INTEGER,
    customization_key TEXT,
    charge_code INTEGER DEFAULT 0,
    bank_code INTEGER DEFAULT 0,
    guest_count INTEGER DEFAULT 1,
    eligible_guest_count INTEGER DEFAULT 0,
    shift_number INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (pos_client_id, id)
);

-- 4. Order Header (sales_order_2)
CREATE TABLE IF NOT EXISTS sales_order_2 (
    pos_client_id TEXT REFERENCES pos_clients(client_id) ON DELETE CASCADE,
    sales_order_id BIGINT NOT NULL,
    table_id INTEGER NOT NULL,
    tseq_no BIGINT,
    guest_count INTEGER NOT NULL,
    therapist TEXT,
    eligible_guest_count INTEGER DEFAULT 0,
    order_type INTEGER NOT NULL,
    payment_status INTEGER NOT NULL DEFAULT 0,
    applied_discount_id INTEGER,
    is_split_bill INTEGER DEFAULT 0,
    is_combine BOOLEAN DEFAULT FALSE,
    payment_deposit_id INTEGER,
    parent_sales_order_id INTEGER,
    timestamp_column TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    posting_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    disc_fix_amt NUMERIC(12, 2) DEFAULT 0.0,
    disc_percent NUMERIC(12, 2) DEFAULT 0.0,
    applied_coupon_id INTEGER,
    coupon_serial TEXT,
    coupon_type INTEGER,
    coupon_value NUMERIC(12, 2),
    is_redeemed INTEGER DEFAULT 0,
    remarks TEXT,
    paid_at TIMESTAMP WITH TIME ZONE,
    stardeals_serial TEXT,
    supabase_sales_order_id BIGINT,
    PRIMARY KEY (pos_client_id, sales_order_id)
);

-- 5. Order Item (sales_order_item)
CREATE TABLE IF NOT EXISTS sales_order_item (
    pos_client_id TEXT REFERENCES pos_clients(client_id) ON DELETE CASCADE,
    order_item_id BIGINT NOT NULL,
    sales_order_id BIGINT NOT NULL,
    item_barcode TEXT,
    quantity NUMERIC(12, 2) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    timestamp_column TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    item_modifiers TEXT,
    customization TEXT,
    is_disc_exempt BOOLEAN NOT NULL DEFAULT FALSE,
    item_discount NUMERIC(12, 2),
    special_price NUMERIC(12, 2) DEFAULT 0.0,
    posting_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (pos_client_id, order_item_id),
    FOREIGN KEY (pos_client_id, sales_order_id) REFERENCES sales_order_2(pos_client_id, sales_order_id) ON DELETE CASCADE
);

-- 6. Indexes for optimal query performance
CREATE INDEX IF NOT EXISTS idx_pos_clients_last_heartbeat ON pos_clients(last_heartbeat);
CREATE INDEX IF NOT EXISTS idx_sales_m1_client_tseq ON sales_m1(pos_client_id, tseq_no);
CREATE INDEX IF NOT EXISTS idx_sales_m2_client_tseq ON sales_m2(pos_client_id, tseq_no);
CREATE INDEX IF NOT EXISTS idx_sales_order_2_client_id ON sales_order_2(pos_client_id, sales_order_id);
CREATE INDEX IF NOT EXISTS idx_sales_order_item_client_order ON sales_order_item(pos_client_id, sales_order_id);
