-- Per-item "special instructions" — user-defined questions attached to a menu
-- item (e.g. steak → "How done? rare/well-done", "What cut?"). Distinct from the
-- POS's priced option-group/modifier system: these are non-priced, support plain
-- suggested choices AND/OR free text, single or multiple selection, and can be
-- required via min/max.
--
-- Definitions are a shared catalog (like "Department"/"Category"/item in 0009):
-- identity PK, no pos_client_id, realtime-published so edits live-refresh on both
-- the POS and the web table-ordering app. Answers ride on each order line in a new
-- sales_order_item.special_instructions JSON column.
--
-- Idempotent: CREATE ... IF NOT EXISTS / ADD COLUMN IF NOT EXISTS / guarded
-- publication adds make re-runs a no-op.

-- ── Question (group) ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS item_instruction_group (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_barcode     TEXT NOT NULL REFERENCES item(barcode) ON DELETE CASCADE,
  label            TEXT NOT NULL,
  -- Required ⇔ min_select > 0. Single-select ⇔ max_select = 1; multiple ⇔ > 1
  -- (NULL = unlimited). allow_free_text adds a typed-answer field (on its own for
  -- a free-text-only question, or alongside choices for "both").
  min_select       INTEGER DEFAULT 0,
  max_select       INTEGER DEFAULT 1,
  allow_free_text  INTEGER DEFAULT 0,
  display_order    INTEGER DEFAULT 0,
  group_status     INTEGER DEFAULT 1,
  timestamp_column TIMESTAMPTZ DEFAULT now(),
  d_tran_date      TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_item_instruction_group_barcode
  ON item_instruction_group (item_barcode);

-- ── Suggested choice (plain label, no backing product / price) ───
CREATE TABLE IF NOT EXISTS item_instruction_choice (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id         BIGINT NOT NULL REFERENCES item_instruction_group(id) ON DELETE CASCADE,
  label            TEXT NOT NULL,
  display_order    INTEGER DEFAULT 0,
  choice_status    INTEGER DEFAULT 1,
  timestamp_column TIMESTAMPTZ DEFAULT now(),
  d_tran_date      TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_item_instruction_choice_group
  ON item_instruction_choice (group_id);

-- ── Answers on the order line ────────────────────────────────────
-- JSON array: [{ "group_id": <int>, "label": <str>, "choices": [<str>,...],
--               "free_text": <str|null> }, ...]. Nullable; POS-punched lines
-- without answers leave it NULL. Part of the "don't combine" key so two same-
-- barcode lines with different instructions stay separate.
ALTER TABLE sales_order_item
  ADD COLUMN IF NOT EXISTS special_instructions TEXT;

-- ── Realtime for the definition tables ───────────────────────────
ALTER TABLE item_instruction_group REPLICA IDENTITY FULL;
ALTER TABLE item_instruction_choice REPLICA IDENTITY FULL;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE item_instruction_group;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE item_instruction_choice;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
