-- Adds a globally-unique, auto-incrementing SO Number on the consolidator.
-- Used by terminals (when connected with sync_sales_orders enabled) to print
-- a non-colliding "SO Number" on receipts. Terminals without the consolidator
-- continue to fall back to the local sales_order_id.

ALTER TABLE sales_order_2
  ADD COLUMN IF NOT EXISTS so_number BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE;
