-- Mirrors the maintenance / master-data tables on the consolidator so every
-- terminal shares one catalog when the `sync_maintenance_data` flag is on:
-- departments, categories, items, users + access levels, discounts, charges
-- and banks.
--
-- Unlike the table-layout / usage-log tables these are a SHARED catalog: rows
-- are not owned per-terminal, so there is no `pos_client_id` column and no
-- revision trigger — every terminal reads and writes the same rows by primary
-- key. Identity PKs use GENERATED BY DEFAULT so the app can upsert rows with an
-- explicit key (updates + one-time catalog seeding) as well as let the server
-- assign new ones.
--
-- discount / charge_payment / bank keep sqlite's "code = id" convention. sqlite
-- does this with an AFTER INSERT trigger; here we use a BEFORE INSERT trigger
-- fed by the column's default sequence so the value is present in the INSERT ...
-- RETURNING the client reads back.

-- ── Departments ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Department" (
  dept_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dept_code        TEXT,
  dept_desc        TEXT NOT NULL,
  dept_status      INTEGER DEFAULT 1,
  timestamp_column TIMESTAMPTZ DEFAULT now(),
  d_tran_date      TIMESTAMPTZ DEFAULT now()
);

-- ── Categories ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Category" (
  category_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_code            TEXT,
  dept_code                TEXT,
  category_desc            TEXT NOT NULL,
  category_status          INTEGER DEFAULT 1,
  recommended_category_id  INTEGER,
  department               BIGINT,
  ordering_index           INTEGER,
  is_available_in_web_table INTEGER DEFAULT 1,
  timestamp_column         TIMESTAMPTZ DEFAULT now(),
  d_tran_date              TIMESTAMPTZ DEFAULT now()
);

-- ── Items ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS item (
  id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  barcode                    TEXT UNIQUE,
  item_code                  TEXT UNIQUE,
  item_desc                  TEXT NOT NULL,
  item_details               TEXT,
  label_name                 TEXT,
  is_label_same_with_receipt INTEGER DEFAULT 1,
  item_status                INTEGER DEFAULT 1,
  print_desc                 TEXT,
  category                   BIGINT,
  dept                       BIGINT,
  cost_price                 REAL,
  mark_up                    REAL,
  price                      REAL,
  special_price              REAL,
  price_1                    REAL,
  price_2                    REAL,
  price_3                    REAL,
  price_4                    REAL,
  price_5                    REAL,
  conv_qty                   REAL DEFAULT 1.0,
  d_tran_date                TIMESTAMPTZ DEFAULT now(),
  date_change                TIMESTAMPTZ DEFAULT now(),
  disc_amt                   REAL DEFAULT 0.0,
  assigned_printer           TEXT,
  disc_exempt                INTEGER DEFAULT 0,
  non_vat                    INTEGER DEFAULT 0,
  finished_good              INTEGER DEFAULT 0,
  composition                INTEGER DEFAULT 0,
  raw_material               INTEGER DEFAULT 0,
  is_combo                   INTEGER DEFAULT 0,
  disp_image                 TEXT,
  button_index               INTEGER,
  is_gift_check              INTEGER DEFAULT 0,
  gift_check_code            INTEGER,
  min_lvl                    REAL DEFAULT 0,
  max_lvl                    REAL DEFAULT 0,
  unit                       INTEGER DEFAULT 1,
  disc_cap_amt               REAL DEFAULT 0.0,
  disc_cap_perc              REAL DEFAULT 0.0,
  can_be_grams               INTEGER DEFAULT 0,
  can_be_pcs                 INTEGER DEFAULT 0,
  can_be_ml                  INTEGER DEFAULT 0,
  show_on_kds                INTEGER DEFAULT 1,
  estimated_prep_time        INTEGER,
  area                       INTEGER DEFAULT 0,
  bulk_units                 TEXT,
  bulk_conversion            REAL DEFAULT 0.0,
  is_solid                   INTEGER DEFAULT 0,
  is_liquid                  INTEGER DEFAULT 0,
  is_bundle                  INTEGER DEFAULT 0,
  is_hidden                  INTEGER DEFAULT 0,
  is_buffet                  INTEGER DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_item_category ON item (category);
CREATE INDEX IF NOT EXISTS idx_item_dept ON item (dept);

-- ── Access levels + users ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users_access_level (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             TEXT NOT NULL,
  sales_entry      INTEGER NOT NULL DEFAULT 0,
  sales_order      INTEGER NOT NULL DEFAULT 0,
  sales_reading    INTEGER NOT NULL DEFAULT 0,
  sales_inquiry    INTEGER NOT NULL DEFAULT 0,
  file_maintenance INTEGER NOT NULL DEFAULT 0,
  admin_mode       INTEGER NOT NULL DEFAULT 0,
  dtr_menu         INTEGER NOT NULL DEFAULT 0,
  self_order_kiosk INTEGER NOT NULL DEFAULT 0,
  inventory        INTEGER NOT NULL DEFAULT 0,
  status           INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS user_access (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  access_level_id BIGINT NOT NULL REFERENCES users_access_level(id) ON DELETE CASCADE,
  access_key      TEXT NOT NULL,
  access_value    INTEGER NOT NULL DEFAULT 0,
  timestamp_column TIMESTAMPTZ DEFAULT now(),
  UNIQUE (access_level_id, access_key)
);

CREATE TABLE IF NOT EXISTS "user" (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  access_level_id BIGINT NOT NULL,
  name            TEXT NOT NULL,
  password        TEXT NOT NULL,
  status          INTEGER NOT NULL DEFAULT 1
);

-- ── Discounts (disc_code = id) ───────────────────────────────────
CREATE TABLE IF NOT EXISTS "Discount" (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY,
  disc_code                BIGINT PRIMARY KEY DEFAULT nextval(pg_get_serial_sequence('"Discount"', 'id')),
  disc_name                TEXT,
  disc_perc                REAL,
  disc_amt                 REAL,
  disc_limit               TEXT,
  timestamp_column         TIMESTAMPTZ DEFAULT now(),
  d_tran_date              TIMESTAMPTZ DEFAULT now(),
  disc_limit_expr          TEXT,
  vip_disc                 INTEGER DEFAULT 0,
  l_disc_1                 INTEGER DEFAULT 0,
  l_employee               INTEGER DEFAULT 0,
  l_pwd                    INTEGER DEFAULT 0,
  l_gpc                    INTEGER DEFAULT 0,
  disc_type                INTEGER DEFAULT 0,
  l_custom                 INTEGER DEFAULT 0,
  disc_status              INTEGER DEFAULT 1,
  should_ask_details       INTEGER DEFAULT 1,
  include_vat_priv         INTEGER DEFAULT 0,
  vat_priv_percent         REAL DEFAULT 12,
  recompute_vat            INTEGER DEFAULT 0,
  use_guest_prorate        INTEGER DEFAULT 0,
  use_special_price        INTEGER DEFAULT 0,
  is_zero_rated            INTEGER DEFAULT 0,
  bypass_nonvat            INTEGER DEFAULT 0,
  min_guests               INTEGER,
  max_guests               INTEGER,
  is_transaction_discount  INTEGER DEFAULT 0
);

-- ── Charges (charge_code = id) ───────────────────────────────────
CREATE TABLE IF NOT EXISTS charge_payment (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
  charge_code         BIGINT PRIMARY KEY DEFAULT nextval(pg_get_serial_sequence('charge_payment', 'id')),
  charge_desc         TEXT,
  charge_no           INTEGER,
  date                TIMESTAMPTZ,
  tseq_no             INTEGER,
  timestamp_column    TIMESTAMPTZ DEFAULT now(),
  d_tran_date         TIMESTAMPTZ DEFAULT now(),
  charge_amt          NUMERIC(10, 2),
  z_number            INTEGER,
  cashier             INTEGER,
  approv_no           TEXT,
  charge_status       INTEGER DEFAULT 1,
  charge_payment_type INTEGER
);

-- ── Banks (bank_code = id) ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS bank (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
  bank_code        BIGINT PRIMARY KEY DEFAULT nextval(pg_get_serial_sequence('bank', 'id')),
  bank_name        TEXT NOT NULL,
  timestamp_column TIMESTAMPTZ DEFAULT now(),
  d_tran_date      TIMESTAMPTZ DEFAULT now(),
  bank_status      INTEGER DEFAULT 1,
  card_type        INTEGER
);

-- ── Holidays ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS holidays (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  holiday_date TEXT UNIQUE NOT NULL,  -- YYYY-MM-DD
  description  TEXT,
  is_active    INTEGER DEFAULT 1
);

-- ── Discount availability rules ──────────────────────────────────
-- FK to Discount(disc_code) with ON DELETE CASCADE so "Clear Discounts"
-- also clears the rules tied to each discount.
CREATE TABLE IF NOT EXISTS discount_availability (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  discount_code BIGINT NOT NULL REFERENCES "Discount"(disc_code) ON DELETE CASCADE,
  day           TEXT,  -- Monday, Tuesday, etc.
  week_of_month TEXT,  -- 1,2,3,4,5,L
  start_time    TEXT,  -- HH:mm
  end_time      TEXT,  -- HH:mm
  date_start    TEXT,  -- YYYY-MM-DD
  date_end      TEXT,  -- YYYY-MM-DD
  is_active     INTEGER DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_discount_availability_code ON discount_availability (discount_code);

-- The PRIMARY KEY (code) shares the identity column's sequence via its DEFAULT,
-- so a plain INSERT gets a fresh code automatically and the client can read it
-- back through RETURNING. `id` mirrors the same value for row-shape parity with
-- the sqlite model (updateStatus filters charge_payment / bank by `id`).
CREATE OR REPLACE FUNCTION sync_code_from_id() RETURNS TRIGGER AS $$
BEGIN
  -- Whichever of (id, <code>) the caller supplied, fill in the other.
  IF TG_TABLE_NAME = 'Discount' THEN
    IF NEW.id IS NULL THEN NEW.id := NEW.disc_code; END IF;
    IF NEW.disc_code IS NULL THEN NEW.disc_code := NEW.id; END IF;
  ELSIF TG_TABLE_NAME = 'charge_payment' THEN
    IF NEW.id IS NULL THEN NEW.id := NEW.charge_code; END IF;
    IF NEW.charge_code IS NULL THEN NEW.charge_code := NEW.id; END IF;
  ELSIF TG_TABLE_NAME = 'bank' THEN
    IF NEW.id IS NULL THEN NEW.id := NEW.bank_code; END IF;
    IF NEW.bank_code IS NULL THEN NEW.bank_code := NEW.id; END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_discount_code ON "Discount";
CREATE TRIGGER trg_discount_code BEFORE INSERT ON "Discount"
  FOR EACH ROW EXECUTE FUNCTION sync_code_from_id();

DROP TRIGGER IF EXISTS trg_charge_payment_code ON charge_payment;
CREATE TRIGGER trg_charge_payment_code BEFORE INSERT ON charge_payment
  FOR EACH ROW EXECUTE FUNCTION sync_code_from_id();

DROP TRIGGER IF EXISTS trg_bank_code ON bank;
CREATE TRIGGER trg_bank_code BEFORE INSERT ON bank
  FOR EACH ROW EXECUTE FUNCTION sync_code_from_id();

-- ── Realtime for the menu master tables ──────────────────────────
-- departments / categories / items drive the in-app menu, which every
-- terminal reads from MasterFileBloc. Publish their changes so a catalog edit
-- on one terminal live-refreshes the others (ConsolidatorRealtimeListener).
-- The other maintenance tables (users, discounts, charges, banks) are not
-- published — their screens refresh on entry, which is enough for rarely-edited
-- config.
ALTER TABLE "Department" REPLICA IDENTITY FULL;
ALTER TABLE "Category" REPLICA IDENTITY FULL;
ALTER TABLE item REPLICA IDENTITY FULL;

-- Add to the realtime publication. Wrapped so re-running this migration is a
-- no-op instead of erroring on "table is already member of publication".
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE "Department";
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE "Category";
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE item;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
