-- Server-authoritative sales order / item IDs.
--
-- Previously each terminal picked its own sales_order_id / order_item_id
-- (MAX per pos_client_id + 1), so ids were only unique *per terminal* and the
-- tables used a composite PK (pos_client_id, id). That forced owner-resolution
-- logic on every read/write and was race-prone.
--
-- This migration makes the consolidator the single source of ids: both columns
-- become globally-unique IDENTITY sequences (same mechanism as so_number in
-- 0005) and the SOLE primary key. pos_client_id is demoted to a plain
-- ownership/audit column (still FK to pos_clients, just no longer part of the
-- key). Terminals stop sending ids on insert and read the assigned value back.
--
-- NOTE: this wipes existing sales-order data (test data) so the fresh IDENTITY
-- sequences start clean and there are no leftover per-terminal duplicates.

BEGIN;

-- 1. Wipe existing sales-order data. RESTART IDENTITY resets so_number too.
TRUNCATE TABLE sales_order_item, sales_order_2 RESTART IDENTITY CASCADE;

-- 2. Drop every FK from sales_order_item → sales_order_2, then both composite
--    primary keys. There are two such FKs: the one added in 0002
--    (fk_sales_order_item_sales_order_2) and the original inline composite FK
--    auto-named by Postgres when the table was created
--    (sales_order_item_pos_client_id_sales_order_id_fkey). Both depend on the
--    composite PK index, so both must go before the PK can be dropped. The
--    DO block also catches any other differently-named FK between the two
--    tables so this works regardless of how the constraint was named.
ALTER TABLE sales_order_item DROP CONSTRAINT IF EXISTS fk_sales_order_item_sales_order_2;
ALTER TABLE sales_order_item DROP CONSTRAINT IF EXISTS sales_order_item_pos_client_id_sales_order_id_fkey;
DO $$
DECLARE
  con RECORD;
BEGIN
  FOR con IN
    SELECT conname
    FROM pg_constraint
    WHERE conrelid = 'sales_order_item'::regclass
      AND confrelid = 'sales_order_2'::regclass
      AND contype = 'f'
  LOOP
    EXECUTE format('ALTER TABLE sales_order_item DROP CONSTRAINT %I', con.conname);
  END LOOP;
END $$;

ALTER TABLE sales_order_item DROP CONSTRAINT IF EXISTS sales_order_item_pkey;
ALTER TABLE sales_order_2   DROP CONSTRAINT IF EXISTS sales_order_2_pkey;

-- 3. Make the id columns server-assigned IDENTITY (Postgres allows more than
--    one identity column per table, so this coexists with so_number).
ALTER TABLE sales_order_2   ALTER COLUMN sales_order_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE sales_order_item ALTER COLUMN order_item_id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 4. New sole primary keys on the now-global ids.
ALTER TABLE sales_order_2    ADD CONSTRAINT sales_order_2_pkey   PRIMARY KEY (sales_order_id);
ALTER TABLE sales_order_item ADD CONSTRAINT sales_order_item_pkey PRIMARY KEY (order_item_id);

-- 5. Re-add the header→item cascade FK as a single-column reference.
ALTER TABLE sales_order_item
  ADD CONSTRAINT fk_sales_order_item_sales_order_2
  FOREIGN KEY (sales_order_id) REFERENCES sales_order_2(sales_order_id) ON DELETE CASCADE;

-- 6. Swap the composite ownership indexes for ones that still make the
--    pos_client_id / sales_order_id lookups fast now that the key changed.
DROP INDEX IF EXISTS idx_sales_order_2_client_id;
DROP INDEX IF EXISTS idx_sales_order_item_client_order;
CREATE INDEX IF NOT EXISTS idx_sales_order_2_pos_client_id ON sales_order_2(pos_client_id);
CREATE INDEX IF NOT EXISTS idx_sales_order_item_sales_order_id ON sales_order_item(sales_order_id);
CREATE INDEX IF NOT EXISTS idx_sales_order_item_pos_client_id ON sales_order_item(pos_client_id);

COMMIT;

-- RLS REVIEW: policies that referenced (pos_client_id, id) as the row key still
-- work as plain row filters, but re-verify any policy that assumed the composite
-- PK. pos_client_id remains a real column and its pos_clients FK is untouched.
