-- Adds the item_availability table to the consolidator (shared catalog) so an
-- item's per-item scheduling rules travel with it under the
-- `sync_maintenance_data` flag, mirroring discount_availability (0009).
--
-- Keyed by item_barcode; FK to item(barcode) with ON DELETE CASCADE so
-- "Clear Master File" (which removes items) also clears the rules tied to each
-- item. Identity PK uses GENERATED BY DEFAULT for upsert parity with the rest
-- of the maintenance tables.

CREATE TABLE IF NOT EXISTS item_availability (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_barcode        TEXT NOT NULL REFERENCES item(barcode) ON DELETE CASCADE,
  day                 TEXT,  -- Monday, Tuesday, etc.
  week_of_month       TEXT,  -- 1,2,3,4,5,L
  start_time          TEXT,  -- HH:mm
  end_time            TEXT,  -- HH:mm
  date_start          TEXT,  -- YYYY-MM-DD
  date_end            TEXT,  -- YYYY-MM-DD
  is_active           INTEGER DEFAULT 1,
  available_on_holiday INTEGER DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_item_availability_barcode ON item_availability (item_barcode);
