-- Serving status for order lines, tracked per printed TICKET.
--
-- Web-order tickets printed by the print master (0018/0019) carry a CODE128
-- barcode. A separate scanning app scans it when the item is handed over and the
-- served quantity advances.
--
-- Why a ticket table and not a code on the line: the web app COMBINES the same
-- item barcode into one `sales_order_item` row, so "Item A x2" followed later by
-- "Item A x1" is a single row of qty 3. A per-line code would print once and one
-- scan would serve all three. Each *printed instance* needs its own record, so
-- the print master mints one `order_item_ticket` per delta it prints (the delta
-- being `quantity - printed_quantity`, the same boundary 0019 already claims
-- atomically). Scanning a ticket advances the line by THAT ticket's quantity.
--
--   order_item_ticket.ticket_code     — the barcode payload, assigned by
--     Postgres from a sequence ('T000123'). Opaque and short (7 chars) so it
--     stays readable on 58mm paper; the scanner must never parse ids out of it.
--   order_item_ticket.quantity        — how much of the line this ticket covers.
--   sales_order_item.item_status      — 'preparing' (default) | 'served'.
--     'served' only once served_quantity reaches the line's full quantity.
--   sales_order_item.served_quantity  — rollup of the served tickets, so a
--     partly-served line reads e.g. 2 of 3.
--
-- The scanning app's only entry point is serve_ticket(p_ticket_code) below; it
-- passes the scanned value verbatim and gets back everything its confirmation UI
-- needs. sales_order_item is already REPLICA IDENTITY FULL and published to
-- supabase_realtime (0016); order_item_ticket is published below, so scans reach
-- POS terminals live.
--
-- Idempotent: CREATE ... IF NOT EXISTS / ADD COLUMN IF NOT EXISTS / CREATE OR
-- REPLACE / guarded publication add make re-runs a no-op.

-- ── Rollup on the order line ─────────────────────────────────────
-- served_quantity first: item_status is GENERATED from it below.
ALTER TABLE sales_order_item
  ADD COLUMN IF NOT EXISTS served_quantity NUMERIC(12, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS served_at       TIMESTAMPTZ;

-- item_status is DERIVED, never stored independently. If it were a plain column
-- it would go stale the moment a line's quantity changed without a scan — the
-- web app merges a re-order of the same item into the existing line, so a fully
-- served "3x A" becomes "4x A" with served_quantity still 3, and a stored status
-- would keep claiming 'served' while a unit was still in the kitchen. As a
-- generated column it cannot disagree with the numbers, whoever changes them.
-- (quantity > 0 keeps a zero-quantity line from reading as served.)
ALTER TABLE sales_order_item
  ADD COLUMN IF NOT EXISTS item_status TEXT
    GENERATED ALWAYS AS (
      CASE WHEN quantity > 0 AND served_quantity >= quantity THEN 'served'
           ELSE 'preparing' END
    ) STORED;

CREATE INDEX IF NOT EXISTS idx_sales_order_item_status
  ON sales_order_item (sales_order_id, item_status);

-- ── One row per printed ticket ───────────────────────────────────
CREATE SEQUENCE IF NOT EXISTS order_item_ticket_code_seq;

CREATE TABLE IF NOT EXISTS order_item_ticket (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_code    TEXT UNIQUE NOT NULL
                 DEFAULT ('T' || to_char(nextval('order_item_ticket_code_seq'), 'FM000000')),
  order_item_id  BIGINT NOT NULL REFERENCES sales_order_item(order_item_id) ON DELETE CASCADE,
  sales_order_id BIGINT,
  -- How much of the line THIS ticket covers: the delta that was printed.
  quantity       NUMERIC(12, 2) NOT NULL,
  ticket_status  TEXT NOT NULL DEFAULT 'preparing',
  printed_at     TIMESTAMPTZ DEFAULT now(),
  served_at      TIMESTAMPTZ,
  -- Which scanner device served it. The scanning app drains a queue in the
  -- background, so served_at alone can't tell you who scanned it.
  served_by      TEXT
);

-- For databases that already created the table without served_by.
ALTER TABLE order_item_ticket
  ADD COLUMN IF NOT EXISTS served_by TEXT;

CREATE INDEX IF NOT EXISTS idx_order_item_ticket_item
  ON order_item_ticket (order_item_id);

-- ── The scanning app's calls ─────────────────────────────────────
-- The scanning app records every scan locally first and drains the queue in the
-- background, so these functions NEVER raise for a business outcome — they
-- return one row per code with a `result` of 'served' | 'already_served' |
-- 'not_found', always echoing `ticket_code` back. Two reasons:
--   1. The drain must mark each queued scan terminally without parsing error
--      strings, and 'already_served' is a NORMAL outcome here (order-slip copies
--      print the same code twice on purpose, and a re-sent queue row replays).
--   2. RAISE aborts the transaction, which would make one bad code in a batch
--      throw away every other code sent with it.
--
-- Exactly-once is still guaranteed: the ticket is locked FOR UPDATE and an
-- already-served ticket never advances the line a second time.
-- Item names live in the shared `item` catalog (0009), hence the join.

-- Dropped first: the original returned a different column set, and adding
-- p_device_id would otherwise leave an ambiguous overload behind.
DROP FUNCTION IF EXISTS serve_ticket(TEXT);
DROP FUNCTION IF EXISTS serve_ticket(TEXT, TEXT);

CREATE FUNCTION serve_ticket(p_ticket_code TEXT, p_device_id TEXT DEFAULT NULL)
RETURNS TABLE (
  ticket_code      TEXT,
  result           TEXT,
  ticket_quantity  NUMERIC,
  order_item_id    BIGINT,
  sales_order_id   BIGINT,
  item_barcode     TEXT,
  item_name        TEXT,
  quantity         NUMERIC,
  served_quantity  NUMERIC,
  item_status      TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_ticket order_item_ticket%ROWTYPE;
  v_code   TEXT := trim(p_ticket_code);
BEGIN
  SELECT * INTO v_ticket
    FROM order_item_ticket t
   WHERE t.ticket_code = v_code
     FOR UPDATE;

  IF NOT FOUND THEN
    RETURN QUERY SELECT v_code, 'not_found'::TEXT, NULL::NUMERIC, NULL::BIGINT,
                        NULL::BIGINT, NULL::TEXT, NULL::TEXT, NULL::NUMERIC,
                        NULL::NUMERIC, NULL::TEXT;
    RETURN;
  END IF;

  IF v_ticket.ticket_status = 'served' THEN
    -- Report the line's CURRENT totals so a replayed scan still renders a
    -- correct confirmation screen.
    RETURN QUERY
    SELECT v_ticket.ticket_code,
           'already_served'::TEXT,
           v_ticket.quantity,
           i.order_item_id,
           i.sales_order_id,
           i.item_barcode,
           COALESCE(m.print_desc, m.item_desc),
           i.quantity,
           i.served_quantity,
           i.item_status
      FROM sales_order_item i
      LEFT JOIN item m ON m.barcode = i.item_barcode
     WHERE i.order_item_id = v_ticket.order_item_id;
    RETURN;
  END IF;

  UPDATE order_item_ticket t
     SET ticket_status = 'served',
         served_at     = now(),
         served_by     = COALESCE(p_device_id, t.served_by)
   WHERE t.id = v_ticket.id;

  -- Advance the line by this ticket's quantity. LEAST() guards against a line
  -- whose quantity was reduced after its tickets were printed. item_status is a
  -- generated column and follows automatically — it must NOT be assigned here.
  UPDATE sales_order_item i
     SET served_quantity = LEAST(i.quantity, i.served_quantity + v_ticket.quantity),
         served_at       = CASE
                             WHEN LEAST(i.quantity, i.served_quantity + v_ticket.quantity) >= i.quantity
                               THEN now()
                             ELSE i.served_at
                           END
   WHERE i.order_item_id = v_ticket.order_item_id;

  RETURN QUERY
  SELECT v_ticket.ticket_code,
         'served'::TEXT,
         v_ticket.quantity,
         i.order_item_id,
         i.sales_order_id,
         i.item_barcode,
         COALESCE(m.print_desc, m.item_desc),
         i.quantity,
         i.served_quantity,
         i.item_status
    FROM sales_order_item i
    LEFT JOIN item m ON m.barcode = i.item_barcode
   WHERE i.order_item_id = v_ticket.order_item_id;
END $$;

GRANT EXECUTE ON FUNCTION serve_ticket(TEXT, TEXT) TO anon, authenticated;

-- Batch form for the background queue drain: one round trip per flush, one row
-- back per code, in the order given. Independent per code — a 'not_found' in the
-- middle doesn't affect the rest.
DROP FUNCTION IF EXISTS serve_tickets(TEXT[]);
DROP FUNCTION IF EXISTS serve_tickets(TEXT[], TEXT);

CREATE FUNCTION serve_tickets(p_ticket_codes TEXT[], p_device_id TEXT DEFAULT NULL)
RETURNS TABLE (
  ticket_code      TEXT,
  result           TEXT,
  ticket_quantity  NUMERIC,
  order_item_id    BIGINT,
  sales_order_id   BIGINT,
  item_barcode     TEXT,
  item_name        TEXT,
  quantity         NUMERIC,
  served_quantity  NUMERIC,
  item_status      TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_code TEXT;
BEGIN
  FOREACH v_code IN ARRAY p_ticket_codes LOOP
    RETURN QUERY SELECT * FROM serve_ticket(v_code, p_device_id);
  END LOOP;
END $$;

GRANT EXECUTE ON FUNCTION serve_tickets(TEXT[], TEXT) TO anon, authenticated;

-- ── Realtime for the ticket table ────────────────────────────────
ALTER TABLE order_item_ticket REPLICA IDENTITY FULL;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE order_item_ticket;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
