-- KDS orders on the consolidator.
--
-- Kitchen orders have always lived in each POS's local sqlite (`kds_orders` /
-- `kds_order_items`), served to the KDS app over that terminal's HTTP + WebSocket
-- gateway. That ties a kitchen screen to one terminal: it only sees orders from
-- the POS it is paired with, and goes dark when that POS does.
--
-- These tables let every terminal write kitchen orders to one shared place and
-- the KDS read them over Supabase realtime — no POS needs to be reachable. The
-- POS switches to writing here with the "Sync KDS Orders" toggle in Consolidator
-- Settings; with it off nothing below is touched.
--
-- Schema mirrors the local sqlite one (see db/config.dart) with two changes,
-- matching what migration 0010 did for sales orders:
--   * `id` is a globally-unique IDENTITY, so two terminals can't collide on the
--     per-terminal autoincrement ids they used locally.
--   * `pos_client_id` records which terminal sent the order (ownership/audit
--     only — the kitchen screen shows every terminal's orders).
--
-- Status rules live in the RPCs at the bottom rather than in each client, so the
-- POS, the KDS and anything added later cannot disagree about what
-- "partial_serving" means, and two stations bumping items at once can't race.
--
-- Idempotent: CREATE ... IF NOT EXISTS / CREATE OR REPLACE / guarded publication
-- adds make re-runs a no-op.

CREATE TABLE IF NOT EXISTS kds_orders (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pos_client_id   TEXT REFERENCES pos_clients(client_id) ON DELETE CASCADE,
  order_number    TEXT,
  created_at      TIMESTAMPTZ DEFAULT now(),
  received_at     TIMESTAMPTZ DEFAULT now(),
  table_number    TEXT,
  customer_name   TEXT,
  order_sequence  INTEGER DEFAULT 1,
  overall_status  TEXT DEFAULT 'preparing',
  completed_at    TIMESTAMPTZ,
  z_read_number   INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS kds_order_items (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id            BIGINT NOT NULL REFERENCES kds_orders(id) ON DELETE CASCADE,
  name                TEXT NOT NULL,
  quantity            INTEGER DEFAULT 1,
  modifiers           TEXT,
  customization       TEXT,
  notes               TEXT,
  barcode             TEXT,
  station             TEXT,
  estimated_prep_time INTEGER,
  category            TEXT,
  status              TEXT DEFAULT 'preparing',
  created_at          TIMESTAMPTZ DEFAULT now(),
  ready_at            TIMESTAMPTZ,
  picked_up_at        TIMESTAMPTZ,
  completed_at        TIMESTAMPTZ,
  cancelled_at        TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_kds_order_items_order_id ON kds_order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_kds_order_items_status   ON kds_order_items (status);
CREATE INDEX IF NOT EXISTS idx_kds_orders_status        ON kds_orders (overall_status);
CREATE INDEX IF NOT EXISTS idx_kds_orders_pos_client_id ON kds_orders (pos_client_id);

-- ── Order status recalculation ───────────────────────────────────
-- The single source of truth for overall_status, ported from the POS's
-- KdsRepository._updateOverallStatus. Cancelled items are ignored; an order with
-- nothing left but cancelled items is itself cancelled.
CREATE OR REPLACE FUNCTION kds_recalc_order_status(p_order_id BIGINT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_active        INTEGER;
  v_preparing     INTEGER;
  v_ready         INTEGER;
  v_dispatched    INTEGER;
  v_completed     INTEGER;
  v_status        TEXT;
BEGIN
  SELECT count(*) FILTER (WHERE status <> 'cancelled'),
         count(*) FILTER (WHERE status = 'preparing'),
         count(*) FILTER (WHERE status = 'ready'),
         count(*) FILTER (WHERE status = 'dispatched'),
         count(*) FILTER (WHERE status = 'completed')
    INTO v_active, v_preparing, v_ready, v_dispatched, v_completed
    FROM kds_order_items
   WHERE order_id = p_order_id;

  IF v_active = 0 THEN
    v_status := 'cancelled';
  ELSIF v_dispatched + v_completed = v_active THEN
    v_status := 'completed';
  ELSIF v_ready = v_active THEN
    v_status := 'dispatched';
  ELSIF v_ready > 0 THEN
    -- Some ready: still cooking → partial_serving, otherwise the rest is
    -- already picked up, which the POS treats as dispatched.
    v_status := CASE WHEN v_preparing > 0 THEN 'partial_serving' ELSE 'dispatched' END;
  ELSIF v_dispatched > 0 OR v_completed > 0 THEN
    v_status := 'partial_served';
  ELSE
    v_status := 'preparing';
  END IF;

  UPDATE kds_orders o
     SET overall_status = v_status,
         completed_at   = CASE WHEN v_status IN ('completed', 'dispatched')
                                 THEN now() ELSE o.completed_at END
   WHERE o.id = p_order_id;

  RETURN v_status;
END $$;

-- ── Item status ──────────────────────────────────────────────────
-- Mirrors KdsRepository.updateItemStatus, including its quirk: a KDS sending
-- 'dispatched' means "done", which is recorded as 'ready' — only the QMS pickup
-- path may mark an item dispatched.
CREATE OR REPLACE FUNCTION kds_set_item_status(p_item_id BIGINT, p_status TEXT)
RETURNS SETOF kds_orders
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_status   TEXT := CASE WHEN p_status = 'dispatched' THEN 'ready' ELSE p_status END;
  v_order_id BIGINT;
BEGIN
  UPDATE kds_order_items i
     SET status       = v_status,
         ready_at     = CASE WHEN v_status = 'ready'      THEN now() ELSE i.ready_at END,
         picked_up_at = CASE WHEN v_status = 'dispatched' THEN now() ELSE i.picked_up_at END,
         completed_at = CASE WHEN v_status = 'completed'  THEN now() ELSE i.completed_at END,
         cancelled_at = CASE WHEN v_status = 'cancelled'  THEN now() ELSE i.cancelled_at END
   WHERE i.id = p_item_id
   RETURNING i.order_id INTO v_order_id;

  IF v_order_id IS NULL THEN
    RAISE EXCEPTION 'kds_item_not_found: %', p_item_id USING ERRCODE = 'P0002';
  END IF;

  PERFORM kds_recalc_order_status(v_order_id);
  RETURN QUERY SELECT * FROM kds_orders WHERE id = v_order_id;
END $$;

-- ── Order status ─────────────────────────────────────────────────
-- Mirrors KdsRepository.updateOrderStatus: completing an order cascades its
-- non-cancelled items to completed.
CREATE OR REPLACE FUNCTION kds_set_order_status(p_order_id BIGINT, p_status TEXT)
RETURNS SETOF kds_orders
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_status = 'completed' THEN
    UPDATE kds_order_items
       SET status       = 'completed',
           completed_at = now()
     WHERE order_id = p_order_id
       AND status <> 'cancelled';
  END IF;

  UPDATE kds_orders o
     SET overall_status = p_status,
         completed_at   = CASE WHEN p_status IN ('completed', 'dispatched')
                                 THEN now() ELSE o.completed_at END
   WHERE o.id = p_order_id;

  RETURN QUERY SELECT * FROM kds_orders WHERE id = p_order_id;
END $$;

-- ── Pickup (QMS) ─────────────────────────────────────────────────
-- Mirrors KdsRepository.pickupOrder: everything already ready (or stamped
-- ready_at) and not yet picked up becomes dispatched.
CREATE OR REPLACE FUNCTION kds_pickup_order(p_order_id BIGINT)
RETURNS SETOF kds_orders
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE kds_order_items
     SET status       = 'dispatched',
         picked_up_at = now()
   WHERE order_id = p_order_id
     AND picked_up_at IS NULL
     AND status <> 'cancelled'
     AND (status = 'ready' OR ready_at IS NOT NULL);

  PERFORM kds_recalc_order_status(p_order_id);
  RETURN QUERY SELECT * FROM kds_orders WHERE id = p_order_id;
END $$;

-- ── Recall ───────────────────────────────────────────────────────
-- Mirrors KdsRepository.recallOrder: 'serving' pulls items back to ready,
-- anything else back to preparing (which also clears ready_at).
CREATE OR REPLACE FUNCTION kds_recall_order(p_order_id BIGINT, p_type TEXT DEFAULT 'full')
RETURNS SETOF kds_orders
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_target TEXT := CASE WHEN p_type = 'serving' THEN 'ready' ELSE 'preparing' END;
BEGIN
  UPDATE kds_orders SET completed_at = NULL WHERE id = p_order_id;

  UPDATE kds_order_items
     SET status       = v_target,
         completed_at = NULL,
         picked_up_at = NULL,
         cancelled_at = NULL,
         ready_at     = CASE WHEN v_target = 'preparing' THEN NULL ELSE ready_at END
   WHERE order_id = p_order_id
     AND status <> 'cancelled';

  PERFORM kds_recalc_order_status(p_order_id);
  RETURN QUERY SELECT * FROM kds_orders WHERE id = p_order_id;
END $$;

GRANT EXECUTE ON FUNCTION kds_recalc_order_status(BIGINT)   TO anon, authenticated;
GRANT EXECUTE ON FUNCTION kds_set_item_status(BIGINT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION kds_set_order_status(BIGINT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION kds_pickup_order(BIGINT)          TO anon, authenticated;
GRANT EXECUTE ON FUNCTION kds_recall_order(BIGINT, TEXT)    TO anon, authenticated;

-- ── Realtime ─────────────────────────────────────────────────────
-- The KDS app runs on realtime alone in consolidator mode: no websocket, no
-- REST. FULL replica identity so UPDATE payloads carry the whole row and the
-- screen can apply an item status change without re-reading.
ALTER TABLE kds_orders      REPLICA IDENTITY FULL;
ALTER TABLE kds_order_items REPLICA IDENTITY FULL;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE kds_orders;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE kds_order_items;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
