-- Durable print queue for web-order slips.
--
-- Web-order slips used to be printed inline by the elected print master, which
-- assumed that one terminal owns every printer in the store. It doesn't: items
-- route to 'Network Printer 1', 'Network Printer 2', 'USB Printer 1'… and a
-- terminal only has some of those configured. printOrderSlips silently skipped
-- the printers it didn't have and reported success, so the master consumed the
-- per-item print claim (printed_quantity) and the slip was lost for good — the
-- catch-up sweep never revisits a line that is already marked printed. The KDS
-- was unaffected because it ignores printer routing, which is why a kitchen
-- screen could look complete while half the paper never came out.
--
-- Now the master ENQUEUES a job per slip and any master-eligible terminal drains
-- the jobs for printers IT owns, so a 'Network Printer 2' slip is printed by
-- whichever terminal actually has that printer — not by whoever won the election.
-- A job is only marked done when a terminal really sent it, so nothing is lost:
-- a printer that is offline, or that no terminal owns yet, keeps the job pending
-- and visible instead of dropping it.
--
-- Idempotent: CREATE ... IF NOT EXISTS / CREATE OR REPLACE make re-runs a no-op.

CREATE TABLE IF NOT EXISTS print_job (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sales_order_id BIGINT,
  -- The slot this slip is routed to ('Network Printer 2', 'USB Printer 1'), or
  -- 'Unassigned' when the item carries no assigned_printer at all.
  printer_name   TEXT NOT NULL,
  copies         INTEGER NOT NULL DEFAULT 1,
  -- The slip is rendered at print time on whichever terminal drains it, so its
  -- paper size and station alias stay local to that terminal.
  payload        JSONB NOT NULL,
  status         TEXT NOT NULL DEFAULT 'pending',  -- pending | printing | done | failed
  attempts       INTEGER NOT NULL DEFAULT 0,
  claimed_by     TEXT,
  claimed_at     TIMESTAMPTZ,
  printed_at     TIMESTAMPTZ,
  last_error     TEXT,
  created_at     TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_print_job_pending
  ON print_job (status, printer_name, id);

-- How long a job may sit in 'printing' before another terminal may take it over.
-- Covers a terminal that died mid-print; long enough that a slow printer on a
-- healthy terminal is never stolen from underneath it.
--   → see the interval literal in claim_print_jobs below (2 minutes).

-- ── Claim ────────────────────────────────────────────────────────
-- Hands the caller up to p_limit pending jobs it can actually print, flipping
-- them to 'printing' in the same statement.
--
-- SKIP LOCKED is what makes several terminals safe to run at once: each grabs a
-- different row instead of blocking or, worse, both printing the same slip.
CREATE OR REPLACE FUNCTION claim_print_jobs(
  p_client_id     TEXT,
  p_printer_names TEXT[],
  p_limit         INTEGER DEFAULT 10
)
RETURNS SETOF print_job
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  WITH claimable AS (
    SELECT j.id
      FROM print_job j
     WHERE j.printer_name = ANY (p_printer_names)
       AND (
             j.status = 'pending'
             -- Stuck: whoever claimed it never reported back.
             OR (j.status = 'printing' AND j.claimed_at < now() - INTERVAL '2 minutes')
           )
     ORDER BY j.id
     LIMIT p_limit
     FOR UPDATE SKIP LOCKED
  )
  UPDATE print_job j
     SET status     = 'printing',
         claimed_by = p_client_id,
         claimed_at = now()
    FROM claimable c
   WHERE j.id = c.id
  RETURNING j.*;
END $$;

-- ── Complete ─────────────────────────────────────────────────────
-- Called only when the terminal actually sent the slip to a printer.
CREATE OR REPLACE FUNCTION complete_print_job(p_id BIGINT)
RETURNS SETOF print_job
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  UPDATE print_job
     SET status     = 'done',
         printed_at = now(),
         last_error = NULL
   WHERE id = p_id
  RETURNING *;
END $$;

-- ── Release ──────────────────────────────────────────────────────
-- The print failed, or the terminal turned out not to have the printer after
-- all. Back to pending for someone else to take, with the reason recorded.
-- After enough tries it becomes 'failed' so a genuinely broken printer stops
-- churning and shows up in the Print Queue panel instead.
CREATE OR REPLACE FUNCTION release_print_job(
  p_id           BIGINT,
  p_error        TEXT DEFAULT NULL,
  p_max_attempts INTEGER DEFAULT 20
)
RETURNS SETOF print_job
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  UPDATE print_job
     SET attempts   = attempts + 1,
         status     = CASE WHEN attempts + 1 >= p_max_attempts THEN 'failed' ELSE 'pending' END,
         claimed_by = NULL,
         claimed_at = NULL,
         last_error = p_error
   WHERE id = p_id
  RETURNING *;
END $$;

-- ── Retry ────────────────────────────────────────────────────────
-- Manual "retry failed" from the POS: puts exhausted jobs back in play.
CREATE OR REPLACE FUNCTION retry_failed_print_jobs()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_count INTEGER;
BEGIN
  UPDATE print_job
     SET status     = 'pending',
         attempts   = 0,
         claimed_by = NULL,
         claimed_at = NULL
   WHERE status = 'failed';
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END $$;

GRANT EXECUTE ON FUNCTION claim_print_jobs(TEXT, TEXT[], INTEGER)      TO anon, authenticated;
GRANT EXECUTE ON FUNCTION complete_print_job(BIGINT)                   TO anon, authenticated;
GRANT EXECUTE ON FUNCTION release_print_job(BIGINT, TEXT, INTEGER)     TO anon, authenticated;
GRANT EXECUTE ON FUNCTION retry_failed_print_jobs()                    TO anon, authenticated;
