-- ═══════════════════════════════════════════════════════════════════
-- 0036  Maintenance sequence resync
-- ═══════════════════════════════════════════════════════════════════
-- Fixes the "adding a discount / category / item overwrites an existing row"
-- bug on the shared maintenance catalog.
--
-- ROOT CAUSE ─ Every maintenance PK is server-assigned from a sequence:
--   * identity PKs        (Department.dept_id, Category.category_id, item.id)
--   * dual "code = id"     (Discount.disc_code, charge_payment.charge_code,
--     shared-sequence tables  bank.bank_code) — both columns draw one sequence.
-- Seeding paths insert rows with an EXPLICIT key (CSV import row[0],
-- pushAllToConsolidator, master-file import). Postgres does NOT advance a
-- GENERATED BY DEFAULT identity / DEFAULT nextval sequence when an explicit
-- value is supplied, so after a seed the sequence sits BEHIND the real MAX(pk).
-- The next interactive add lets the server assign a key, gets a value that
-- already exists, and the upsert's ON CONFLICT (pk) DO UPDATE overwrites that
-- existing row instead of inserting a new one.
--
-- FIX ─ resync every maintenance sequence to GREATEST(existing keys) so the
-- next server-assigned value is guaranteed free. Exposed as an RPC the app can
-- call after any bulk seed / CSV import so the fix self-heals going forward
-- (see ConsolidatorMaintenanceRepository.resyncSequences).
--
-- Applied MANUALLY against Supabase (see consolidator-migrations-manual).

CREATE OR REPLACE FUNCTION resync_maintenance_sequences() RETURNS void AS $$
BEGIN
  -- Identity-PK tables: bump the sequence to MAX(pk).
  PERFORM setval(pg_get_serial_sequence('"Department"', 'dept_id'),
                 GREATEST((SELECT COALESCE(MAX(dept_id), 0) FROM "Department"), 1), true);
  PERFORM setval(pg_get_serial_sequence('"Category"', 'category_id'),
                 GREATEST((SELECT COALESCE(MAX(category_id), 0) FROM "Category"), 1), true);
  PERFORM setval(pg_get_serial_sequence('item', 'id'),
                 GREATEST((SELECT COALESCE(MAX(id), 0) FROM item), 1), true);

  -- Dual "code = id" tables share one sequence between the two columns, so bump
  -- to the max of BOTH so neither a fresh id nor a fresh code can collide.
  PERFORM setval(pg_get_serial_sequence('"Discount"', 'id'),
                 GREATEST((SELECT COALESCE(MAX(id), 0) FROM "Discount"),
                          (SELECT COALESCE(MAX(disc_code), 0) FROM "Discount"), 1), true);
  PERFORM setval(pg_get_serial_sequence('charge_payment', 'id'),
                 GREATEST((SELECT COALESCE(MAX(id), 0) FROM charge_payment),
                          (SELECT COALESCE(MAX(charge_code), 0) FROM charge_payment), 1), true);
  PERFORM setval(pg_get_serial_sequence('bank', 'id'),
                 GREATEST((SELECT COALESCE(MAX(id), 0) FROM bank),
                          (SELECT COALESCE(MAX(bank_code), 0) FROM bank), 1), true);
END;
$$ LANGUAGE plpgsql;

GRANT EXECUTE ON FUNCTION resync_maintenance_sequences() TO anon, authenticated;

-- Heal the current (already-stranded) state once on apply.
SELECT resync_maintenance_sequences();
