-- ═══════════════════════════════════════════════════════════════════
-- 0066  Discount detail fields (dynamic discount details)
-- ═══════════════════════════════════════════════════════════════════
-- Per-discount setup of the details asked when a discount is applied /
-- settled (name, ID, TIN, custom fields…). Configured in Discount
-- Maintenance on any terminal; mirrored into each terminal's local sqlite
-- `discount_detail_field` by DiscountDetailFieldDao + the maintenance-mirror
-- realtime channel, so every POS asks the same fields.
--
-- Natural key (disc_code, field_key): clients upsert on it and never send
-- `id`, so explicit-key seeding cannot strand the identity sequence.
-- Rows are deactivated (status 0), not deleted, so past values keep labels.
--
-- Applied MANUALLY against Supabase (see consolidator-migrations-manual).

CREATE TABLE IF NOT EXISTS discount_detail_field (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  disc_code        BIGINT  NOT NULL,
  field_key        TEXT    NOT NULL,
  label            TEXT    NOT NULL,
  field_type       TEXT    NOT NULL DEFAULT 'text',   -- text | number | date | select
  is_required      INTEGER NOT NULL DEFAULT 0,
  options          TEXT,                              -- JSON array (select)
  min_length       INTEGER,
  max_length       INTEGER,
  pattern          TEXT,                              -- regex
  derive_age_into  TEXT,                              -- field_key filled with age from this date
  legacy_column    TEXT,                              -- name|id_no|tin|address|birthday|child_*
  ordering_index   INTEGER NOT NULL DEFAULT 0,
  print_on_receipt INTEGER NOT NULL DEFAULT 0,
  status           INTEGER NOT NULL DEFAULT 1,
  updated_at       TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT uq_discount_detail_field UNIQUE (disc_code, field_key)
);

CREATE INDEX IF NOT EXISTS idx_discount_detail_field_disc
  ON discount_detail_field (disc_code);

ALTER TABLE discount_detail_field REPLICA IDENTITY FULL;
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE discount_detail_field;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Staged details (sales-order stage) carry the full dynamic value map and,
-- for item / row-level discounts, the sales_order_item they belong to.
ALTER TABLE staged_discount_details ADD COLUMN IF NOT EXISTS sales_order_item_id BIGINT;
ALTER TABLE staged_discount_details ADD COLUMN IF NOT EXISTS extra_json TEXT;
