-- Create counters table
CREATE TABLE IF NOT EXISTS public.counters (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id bigint NOT NULL,
    counter_key text NOT NULL,
    count bigint NOT NULL DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Unique constraint to ensure one counter per key per branch
CREATE UNIQUE INDEX IF NOT EXISTS idx_counters_branch_key ON public.counters(branch_id, counter_key);

-- Trigger for updated_at
CREATE OR REPLACE FUNCTION public.update_counters_modtime()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_counters_modtime
    BEFORE UPDATE ON public.counters
    FOR EACH ROW
    EXECUTE FUNCTION public.update_counters_modtime();

-- RLS Policies
ALTER TABLE public.counters ENABLE ROW LEVEL SECURITY;

-- Allow read/write access based on branch assignment
CREATE POLICY "Enable access for users based on branch" ON public.counters
    FOR ALL
    USING (
        (EXISTS ( SELECT 1
           FROM (pos_profiles p
             JOIN branches b ON (((b.branch_code)::text = (p.branch_code)::text)))
          WHERE ((p.user_id = auth.uid()) AND (b.id = counters.branch_id))))
    );
