-- Create sales_order table
CREATE TABLE IF NOT EXISTS public.sales_order (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_order_id bigint,
    branch_id bigint,
    table_id bigint NOT NULL REFERENCES public.tables(id),
    guest_count int NOT NULL DEFAULT 1,
    eligible_guest_count int NOT NULL DEFAULT 0,
    order_type int NOT NULL DEFAULT 0, -- 0: Dine-in
    payment_status int NOT NULL DEFAULT 0, -- 0: Unpaid
    applied_discount_id bigint,
    is_split_bill boolean DEFAULT false,
    is_combine boolean DEFAULT false,
    payment_deposit_id bigint,
    parent_sales_order_id bigint REFERENCES public.sales_order(id),
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    posting_date timestamp with time zone,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Create sales_order_item table
CREATE TABLE IF NOT EXISTS public.sales_order_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id bigint,
    branch_id bigint,
    sales_order_id bigint NOT NULL REFERENCES public.sales_order(id) ON DELETE CASCADE,
    item_barcode text NOT NULL,
    quantity int NOT NULL DEFAULT 1,
    amount numeric NOT NULL DEFAULT 0,
    item_modifiers text,
    is_disc_exempt boolean DEFAULT false,
    item_discount numeric,
    posting_date timestamp with time zone,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_sales_order_table_id ON public.sales_order(table_id);
CREATE INDEX IF NOT EXISTS idx_sales_order_payment_status ON public.sales_order(payment_status);
CREATE INDEX IF NOT EXISTS idx_sales_order_item_sales_order_id ON public.sales_order_item(sales_order_id);

-- Trigger for updated_at
CREATE OR REPLACE FUNCTION public.update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_sales_order_modtime
    BEFORE UPDATE ON public.sales_order
    FOR EACH ROW
    EXECUTE FUNCTION public.update_modified_column();

CREATE TRIGGER update_sales_order_item_modtime
    BEFORE UPDATE ON public.sales_order_item
    FOR EACH ROW
    EXECUTE FUNCTION public.update_modified_column();

-- RLS Policies
ALTER TABLE public.sales_order ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales_order_item ENABLE ROW LEVEL SECURITY;

-- Allow anonymous access (Adjust as needed for production)
CREATE POLICY "Enable read access for all users" ON public.sales_order FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON public.sales_order_item FOR SELECT USING (true);
